version: '3.7'

services:
  app:
    image: mysocietyorg/caps:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    command: /usr/src/app/script/server
    volumes:
      - ./:/usr/src/app/
      - ./conf/config.py.docker:/usr/src/app/conf/config.py
    environment:
      - REPOSITORY_DB_PASS=${REPOSITORY_DB_PASS:-caps}
      - SECRET_KEY=${SECRET_KEY:-xx}
      - DEBUG=${DEBUG:-1}
      - MAPIT_API_KEY=${MAPIT_API_KEY:-xxx}
      - GOOGLE_ANALYTICS=${GOOGLE_ANALYTICS:-xxx}
      - MAILCHIMP_KEY=${MAILCHIMP_KEY:-xxx}
    depends_on:
      - postgres
      - solr
    ports:
      - ${PORT:-8000}:8000

  postgres:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${REPOSITORY_DB_USER:-caps}
      - POSTGRES_PASSWORD=${REPOSITORY_DB_PASS:-caps}
      - POSTGRES_DB=${REPOSITORY_DB_NAME:-caps}

  solr:
    image: solr:6
    volumes:
      - solr_data:/opt/solr/server/solr/mycores
      - ./conf/schema.xml:/opt/solr/server/solr/configsets/basic_configs/conf/schema.xml
      - ./conf/solrconfig.xml:/opt/solr/server/solr/configsets/basic_configs/conf/solrconfig.xml
    command:
      - solr-precreate
      - caps
      - /opt/solr/server/solr/configsets/basic_configs
    ports:
      - 8983:8983
      
volumes:
  postgres_data:
  solr_data:
