services:
  app:
    image: mysocietyorg/caps-dev:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: /workspaces/caps/script/server
    volumes:
      - solr_data:/opt/solr/server/solr/mycores
      - ./:/workspaces/caps/
      - ./conf/config.py.docker:/workspaces/caps/conf/config.py
    environment:
      - REPOSITORY_DB_PASS=${REPOSITORY_DB_PASS:-caps}
      - SECRET_KEY=${SECRET_KEY:-xx}
      - DEBUG=${DEBUG:-1}
      - MAPIT_API_KEY=${MAPIT_API_KEY:-xxx}
      - GOOGLE_ANALYTICS=${GOOGLE_ANALYTICS:-xxx}
      - GOOGLE_ANALYTICS_SCORECARDS=${GOOGLE_ANALYTICS_SCORECARDS:-xxx}
      - MAILCHIMP_KEY=${MAILCHIMP_KEY:-xxx}
      - PERSONAL_ACCESS_TOKEN=${PERSONAL_ACCESS_TOKEN:-xxx}
      - SCORECARDS_PRIVATE=${SCORECARDS_PRIVATE:-False}
      # this is just a random valid key for fernet
      - VEGALITE_ENCRYPT_KEY=${VEGALITE_ENCRYPT_KEY:-FeVpOxEnN5zplY0M1OWWNh4SRj3Nbn9B9kSF_JxHUjA=}
      - VEGALITE_SERVER_URL=${VEGALITE_SERVER_URL:-xxx}
      - FEEDBACK_EMAIL=${FEEDBACK_EMAIL:-xxx}
      - EMAIL_HOST=${EMAIL_HOST:-xxx}
      - EMAIL_PORT=${EMAIL_PORT:-xxx}


    depends_on:
      - postgres
      - solr
    ports:
      - ${PORT:-8000}:8000
  postgres:
    extends:
      file: docker-compose.yml
      service: postgres

  solr:
    extends:
      file: docker-compose.yml
      service: solr
  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: always
    ports:
      - 1035:1025
      - 8035:8025
    networks:
     default:
       aliases:
         - email.svc

volumes:
  postgres_data:
  solr_data:
