services:
  app:
    image: mysocietyorg/caps-dev:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: /workspaces/caps/script/server
    volumes:
      - solr_data:/opt/solr/server/solr/mycores
      - ./:/workspaces/caps/
      - ./conf/config.py.docker:/workspaces/caps/conf/config.py
    environment:
      - REPOSITORY_DB_PASS=${REPOSITORY_DB_PASS:-caps}
      - SECRET_KEY=${SECRET_KEY:-xx}
      - DEBUG=${DEBUG:-1}
      - MAPIT_API_KEY=${MAPIT_API_KEY:-xxx}
      - GOOGLE_ANALYTICS=${GOOGLE_ANALYTICS:-xxx}
      - MAILCHIMP_KEY=${MAILCHIMP_KEY:-xxx}
      - PERSONAL_ACCESS_TOKEN=${PERSONAL_ACCESS_TOKEN:-xxx}
      - SCORECARDS_PRIVATE=${SCORECARDS_PRIVATE:-False}
    depends_on:
      - postgres
      - solr
    ports:
      - ${PORT:-8000}:8000
  postgres:
    extends:
      file: docker-compose.yml
      service: postgres

  solr:
    extends:
      file: docker-compose.yml
      service: solr

volumes:
  postgres_data:
  solr_data: