version: '3.7'

services:
  app:
    image: mysocietyorg/caps:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    command: /usr/src/app/script/server
    volumes:
      - ./:/usr/src/app/
      - ./conf/config.py.docker:/usr/src/app/conf/config.py
    environment:
      - REPOSITORY_DB_PASS=${REPOSITORY_DB_PASS:-caps}
      - SECRET_KEY=${SECRET_KEY:-xx}
      - DEBUG=${DEBUG:-1}
      - MAPIT_API_KEY=${MAPIT_API_KEY:-xxx}
      - GOOGLE_ANALYTICS=${GOOGLE_ANALYTICS:-xxx}
      - GOOGLE_ANALYTICS_SCORECARDS=${GOOGLE_ANALYTICS_SCORECARDS:-xxx}
      - MAILCHIMP_KEY=${MAILCHIMP_KEY:-xxx}
      - PERSONAL_ACCESS_TOKEN=${PERSONAL_ACCESS_TOKEN:-xxx}
      - SCORECARDS_PRIVATE=${SCORECARDS_PRIVATE:-False}
      - HIDE_DEBUG_TOOLBAR=${HIDE_DEBUG_TOOLBAR:-False}
      # this is just a random valid key for fernet
      - VEGALITE_ENCRYPT_KEY=${VEGALITE_ENCRYPT_KEY:-FeVpOxEnN5zplY0M1OWWNh4SRj3Nbn9B9kSF_JxHUjA=}
      - VEGALITE_SERVER_URL=${VEGALITE_SERVER_URL:-xxx}
      - FEEDBACK_EMAIL=${FEEDBACK_EMAIL:-xxx}
      - EMAIL_HOST=${EMAIL_HOST:-localhost}
      - EMAIL_PORT=${EMAIL_PORT:-25}

    depends_on:
      - postgres
      - solr
    ports:
      - ${PORT:-8000}:8000
      - 25:25

  postgres:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${REPOSITORY_DB_USER:-caps}
      - POSTGRES_PASSWORD=${REPOSITORY_DB_PASS:-caps}
      - POSTGRES_DB=${REPOSITORY_DB_NAME:-caps}

  solr:
    image: solr:6.5
    volumes:
      - solr_data:/opt/solr/server/solr/mycores
      - ./conf/schema.xml:/opt/solr/server/solr/configsets/basic_configs/conf/schema.xml
      - ./conf/solrconfig.xml:/opt/solr/server/solr/configsets/basic_configs/conf/solrconfig.xml
      - ./script/update_solr_schema:/opt/docker-solr/scripts/update_solr_schema
    command:
      - solr-precreate
      - caps
      - /opt/solr/server/solr/configsets/basic_configs
    ports:
      - 8983:8983
      
volumes:
  postgres_data:
  solr_data:
