version: '3.7'

services:
  app:
    image: mysociety/caps:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
      cache_from:
       - ghcr.io/mysociety/caps:master
    command: /workspaces/caps/script/server
    volumes:
      - ./:/workspaces/caps/
      - ./conf/config.py.docker:/workspaces/caps/conf/config.py
    environment:
      - REPOSITORY_DB_PASS=${REPOSITORY_DB_PASS:-caps}
      - SECRET_KEY=${SECRET_KEY:-xx}
      - DEBUG=${DEBUG:-True}
      - MAPIT_API_KEY=${MAPIT_API_KEY:-xxx}
      - GOOGLE_ANALYTICS=${GOOGLE_ANALYTICS}
      - GOOGLE_MEASUREMENT_PROTOCOL_SECRET=${GOOGLE_MEASUREMENT_PROTOCOL_SECRET}
      - GOOGLE_TAG_MANAGER=${GOOGLE_TAG_MANAGER}
      - DATA_REPO_TOKEN=${DATA_REPO_TOKEN:-xxx}
      - GOOGLE_ANALYTICS_SCORECARDS=${GOOGLE_ANALYTICS_SCORECARDS}
      - MAILCHIMP_KEY=${MAILCHIMP_KEY:-xxx}
      - PERSONAL_ACCESS_TOKEN=${PERSONAL_ACCESS_TOKEN:-xxx}
      - SCORECARDS_PRIVATE=${SCORECARDS_PRIVATE:-False}
      - HIDE_DEBUG_TOOLBAR=${HIDE_DEBUG_TOOLBAR:-False}
      # this is just a random valid key for fernet
      - VEGALITE_ENCRYPT_KEY=${VEGALITE_ENCRYPT_KEY:-FeVpOxEnN5zplY0M1OWWNh4SRj3Nbn9B9kSF_JxHUjA=}
      - VEGALITE_SERVER_URL=${VEGALITE_SERVER_URL:-xxx}
      - FEEDBACK_EMAIL=${FEEDBACK_EMAIL:-xxx}
      - EMAIL_HOST=${EMAIL_HOST:-localhost}
      - EMAIL_PORT=${EMAIL_PORT:-25}
      - PLAN_YEAR=${PLAN_YEAR:-2023}
      - METHODOLOGY_YEAR=${METHODOLOGY_YEAR:-2025}

    depends_on:
      - postgres
      - solr
    ports:
      - ${PORT:-8000}:8000
      - 25:25

  postgres:
    image: postgres:13
    volumes:
      - postgres_data_13:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${REPOSITORY_DB_USER:-caps}
      - POSTGRES_PASSWORD=${REPOSITORY_DB_PASS:-caps}
      - POSTGRES_DB=${REPOSITORY_DB_NAME:-caps}

  solr:
    image: solr:6.5
    volumes:
      - solr_data:/opt/solr/server/solr/mycores
      - ./conf/schema.xml:/opt/solr/server/solr/configsets/basic_configs/conf/schema.xml
      - ./conf/solrconfig.xml:/opt/solr/server/solr/configsets/basic_configs/conf/solrconfig.xml
      - ./script/update_solr_schema:/opt/docker-solr/scripts/update_solr_schema
    command:
      - solr-precreate
      - caps
      - /opt/solr/server/solr/configsets/basic_configs
    ports:
      - 8983:8983
      
volumes:
  postgres_data_13:
  solr_data:
