# Generated by Django 2.2.8 on 2020-10-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0006_auto_20201019_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandocument',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
