# Generated by Django 2.2.8 on 2020-10-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0008_auto_20201019_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandocument',
            name='notes',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
