# Generated by Django 2.2.8 on 2020-10-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0009_auto_20201019_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='council',
            name='authority_type',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
