# Generated by Django 2.2.8 on 2020-10-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0010_auto_20201019_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='council',
            name='whatdotheyknow_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
