# Generated by Django 2.2.8 on 2020-10-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0012_auto_20201023_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='council',
            name='authority_type',
            field=models.CharField(blank=True, choices=[('CC', 'City of London'), ('COMB', 'Combined Authority'), ('CTY', 'County Council'), ('LBO', 'London Borough'), ('MD', 'Metropolitan District'), ('NMD', 'Non-Metropolitan District'), ('UA', 'Unitary Authority')], max_length=4),
        ),
    ]
