# Generated by Django 2.2.8 on 2020-10-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0012_auto_20201023_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='council',
            name='authority_type',
            field=models.CharField(blank=True, choices=[('CC', 'County council'), ('COMB', 'Combined authority'), ('CTY', 'County'), ('LBO', 'London Borough'), ('MD', 'Metropolitan district'), ('NMD', 'Non-metropolitan district'), ('UA', 'Unitary authority')], max_length=4),
        ),
    ]
