# Generated by Django 2.2.8 on 2020-10-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0015_council_gss_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('source_url', models.URLField(max_length=600)),
                ('name_in_source', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='council',
            name='gss_code',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
