# Generated by Django 2.2.8 on 2020-10-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0018_auto_20201028_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='value',
            field=models.DecimalField(decimal_places=30, max_digits=30),
        ),
    ]
