# Generated by Django 2.2.8 on 2020-10-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0019_auto_20201028_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='value',
            field=models.FloatField(),
        ),
    ]
