# Generated by Django 2.2.8 on 2020-10-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0020_auto_20201028_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='council',
            name='authority_code',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='council',
            name='gss_code',
            field=models.CharField(blank=True, max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='council',
            name='whatdotheyknow_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
