# Generated by Django 2.2.8 on 2020-11-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0022_council_combined_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='council',
            name='related_authorities',
            field=models.ManyToManyField(blank=True, related_name='_council_related_authorities_+', to='caps.Council'),
        ),
    ]
