# Generated by Django 3.1.2 on 2020-10-30 18:15

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0022_council_combined_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandocument',
            name='text_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='plandocument',
            index=django.contrib.postgres.indexes.GinIndex(fields=['text_search'], name='caps_plando_text_se_b16b55_gin'),
        ),
    ]
