# Generated by Django 2.2.24 on 2021-08-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0026_auto_20210406_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_key', models.SlugField(help_text='A way to arbitrarily group queries. Should be a single word. Example: all-products', max_length=100)),
                ('user_query', models.CharField(help_text='The text the user searched on. Useful for display.', max_length=1000)),
                ('full_query', models.CharField(blank=True, default='', help_text='The full query Haystack generated. Useful for searching again.', max_length=1000)),
                ('result_count', models.PositiveIntegerField(blank=True, default=0)),
                ('inorganic', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Saved Searches',
            },
        ),
    ]
