# Generated by Django 2.2.24 on 2021-09-08 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0027_savedsearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('has_promise', models.BooleanField(blank=True, null=True)),
                ('target_year', models.IntegerField(blank=True, null=True)),
                ('scope', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Council only'), (2, 'Whole area')], null=True)),
                ('text', models.TextField(blank=True)),
                ('source', models.URLField(max_length=600)),
                ('source_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.CharField(blank=True, max_length=800, null=True)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caps.Council')),
            ],
        ),
    ]
