# Generated by Django 2.2.24 on 2021-09-23 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0030_add_emergency_declaration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weighted_total', models.PositiveSmallIntegerField(default=0)),
                ('total', models.PositiveSmallIntegerField(default=0)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caps.Council')),
            ],
        ),
        migrations.CreateModel(
            name='PlanSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_score', models.PositiveSmallIntegerField(null=True)),
                ('max_weighted_score', models.PositiveSmallIntegerField(null=True)),
                ('weight', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanSectionScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('weighted_score', models.PositiveSmallIntegerField(default=0)),
                ('plan_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caps.PlanScore')),
                ('plan_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caps.PlanSection')),
            ],
        ),
    ]
