# Generated by Django 3.2.7 on 2021-11-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0030_add_emergency_declaration'),
    ]

    operations = [
        migrations.AddField(
            model_name='council',
            name='twitter_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='council',
            name='twitter_url',
            field=models.URLField(null=True),
        ),
    ]
