# Generated by Django 3.2.7 on 2021-11-18 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0031_add_plan_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('text', models.TextField(default='', null=True)),
                ('max_score', models.PositiveSmallIntegerField(default=0)),
                ('question_type', models.CharField(max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caps.plansection')),
            ],
        ),
        migrations.CreateModel(
            name='PlanQuestionScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(default='', null=True)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(default='', null=True)),
                ('plan_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caps.planquestion')),
                ('plan_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caps.planscore')),
            ],
        ),
    ]
