# Generated by Django 3.2.7 on 2021-11-10 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caps', '0032_historicalplandocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPromise',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateField(blank=True, editable=False)),
                ('updated_at', models.DateField(blank=True, editable=False)),
                ('has_promise', models.BooleanField(blank=True, null=True)),
                ('target_year', models.IntegerField(blank=True, null=True)),
                ('scope', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Council only'), (2, 'Whole area')], null=True)),
                ('text', models.TextField(blank=True)),
                ('source', models.URLField(max_length=600)),
                ('source_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.CharField(blank=True, max_length=800, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('council', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caps.council')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical promise',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
