# Generated by Django 3.2.10 on 2022-02-02 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0035_auto_20211209_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('description_singular', models.TextField()),
                ('description_plural', models.TextField()),
                ('colour', models.CharField(max_length=50)),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CouncilTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caps.council')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caps.tag')),
            ],
        ),
    ]
