# Generated by Django 3.2.12 on 2022-03-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0037_alter_comparisonlabelassignment_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplandocument',
            name='title',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='plandocument',
            name='title',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
