# Generated by Django 3.2.12 on 2022-04-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0040_add_region_and_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='council',
            name='population',
            field=models.IntegerField(default=0),
        ),
    ]
