# Generated by Django 3.2.13 on 2022-04-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0040_add_region_and_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplandocument',
            name='document_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Action plan'), (2, 'Climate strategy'), (3, 'Summary document'), (4, 'Pre-plan'), (5, 'Meeting minutes'), (6, 'Biodiversity plan'), (7, 'Baseline review'), (8, 'Supporting evidence'), (9, 'Engagement plan'), (10, 'Other plan'), (11, 'Progress report')], null=True),
        ),
        migrations.AlterField(
            model_name='plandocument',
            name='document_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Action plan'), (2, 'Climate strategy'), (3, 'Summary document'), (4, 'Pre-plan'), (5, 'Meeting minutes'), (6, 'Biodiversity plan'), (7, 'Baseline review'), (8, 'Supporting evidence'), (9, 'Engagement plan'), (10, 'Other plan'), (11, 'Progress report')], null=True),
        ),
    ]
