# Generated by Django 3.2.17 on 2023-03-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0043_alter_council_authority_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatype',
            name='collection',
            field=models.CharField(choices=[('em', 'Emissions'), ('po', 'Polling')], default='em', max_length=2),
        ),
    ]
