# Generated by Django 3.2.17 on 2023-04-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0044_datatype_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='council',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='council',
            name='replaced_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='council',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
