# Generated by Django 3.2.17 on 2023-03-28 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0045_auto_20230403_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyphrase', models.CharField(max_length=200)),
                ('nice_phrase', models.CharField(blank=True, max_length=200)),
                ('plan_count', models.IntegerField(default=0)),
                ('average_frequency', models.FloatField(default=0)),
                ('highlight', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='KeyPhrasePairWise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nth_similar', models.IntegerField()),
                ('cosine_similarity', models.FloatField()),
                ('has_common_word', models.BooleanField()),
                ('word_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_a', to='caps.keyphrase')),
                ('word_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_b', to='caps.keyphrase')),
            ],
            options={
                'unique_together': {('word_a', 'word_b')},
            },
        ),
        migrations.CreateModel(
            name='CachedSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_terms', to='caps.plandocument')),
                ('search_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caps.keyphrase')),
            ],
            options={
                'unique_together': {('search_term', 'document')},
            },
        ),
    ]
