# Generated by Django 4.2.17 on 2025-02-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caps", "0048_auto_20240208_1225"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalplandocument",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical plan document",
                "verbose_name_plural": "historical plan documents",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpromise",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical promise",
                "verbose_name_plural": "historical promises",
            },
        ),
        migrations.AlterField(
            model_name="council",
            name="related_authorities",
            field=models.ManyToManyField(
                blank=True, through="caps.Distance", to="caps.council"
            ),
        ),
        migrations.AlterField(
            model_name="historicalplandocument",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalpromise",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
