# Generated by Django 3.2.7 on 2021-12-07 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caps', '0034_savedseach_council_restriction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('text', models.TextField(default='', null=True)),
                ('max_score', models.PositiveSmallIntegerField(default=0)),
                ('question_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlanScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weighted_total', models.PositiveSmallIntegerField(default=0)),
                ('total', models.PositiveSmallIntegerField(default=0)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caps.council')),
            ],
        ),
        migrations.CreateModel(
            name='PlanSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_score', models.PositiveSmallIntegerField(null=True)),
                ('max_weighted_score', models.PositiveSmallIntegerField(null=True)),
                ('weight', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanSectionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('weighted_score', models.PositiveSmallIntegerField(default=0)),
                ('plan_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.planscore')),
                ('plan_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.plansection')),
            ],
        ),
        migrations.CreateModel(
            name='PlanQuestionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(default='', null=True)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(default='', null=True)),
                ('plan_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='league.planquestion')),
                ('plan_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.planscore')),
            ],
        ),
        migrations.AddField(
            model_name='planquestion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.plansection'),
        ),
    ]
