# Generated by Django 3.2.7 on 2022-01-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plansection',
            name='max_score',
        ),
        migrations.RemoveField(
            model_name='plansection',
            name='max_weighted_score',
        ),
        migrations.RemoveField(
            model_name='plansection',
            name='weight',
        ),
        migrations.AddField(
            model_name='plansectionscore',
            name='max_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planscore',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='planscore',
            name='weighted_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='plansectionscore',
            name='weighted_score',
            field=models.FloatField(default=0),
        ),
    ]
