# Generated by Django 3.2.10 on 2022-01-19 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_add_council_filters'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanScoreDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('plan_url', models.URLField(max_length=1000)),
                ('plan_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.planscore')),
            ],
        ),
    ]
