#!/bin/bash

# abort on any errors
set -e

# check that we are in the expected directory
cd `dirname $0`/..

# create plans and media dirs
echo "==> Creating local data directories..."
mkdir -p data/plans
mkdir -p media
mkdir -p static/css

if [ "$1" == "--vagrant" ]; then

  # We're running inside a Vagrant box, so provision accordingly.

  export PYTHONDONTWRITEBYTECODE=1

  # Upgrade pip to a secure version
  curl -L -s https://bootstrap.pypa.io/get-pip.py | python3

  pip3 install --requirement requirements.txt

  # Belt-and-braces - there may be old code, since deleted, for which bytecode was generated
  # before we set PYTHONDONTWRITEBYTECODE above.
  find . -name '*.pyc' -delete
fi
