#!/bin/bash

set -e

cd $(dirname $0)/..

# Flag we're doing a build.
export BUILD_COMMIT=$(git log -1 --pretty=%h)

script/bootstrap

docker build . -t mysocietyorg/caps --build-arg BUILD_COMMIT=$BUILD_COMMIT
docker-compose pull
