#!/bin/sh

# Run this inside the Docker container, eg:
# docker-compose exec app script/install-dev-requirements

# abort on any errors
set -e

# check that we are in the expected directory
cd `dirname $0`/..

# https://shot-scraper.datasette.io
shot-scraper install
playwright install-deps
