#!/bin/sh

# Run this inside the Docker container, eg:
# docker-compose exec app script/install-dev-requirements

cd "$(dirname $0)/.."

[ -f .venv/bin/activate ] && . .venv/bin/activate

pip3 install --requirement requirements.dev.txt
find . -name '*.pyc' -delete

# https://shot-scraper.datasette.io
shot-scraper install
playwright install-deps
