#!/bin/bash

# abort on any errors
set -e

# check that we are in the expected directory
cd "$(dirname $BASH_SOURCE)"/..

[ -f .venv/bin/activate ] && source .venv/bin/activate

poetry run ./manage.py collectstatic --noinput
