#!/bin/bash
#
# script/setup-in-docker: Set up application for the first time after cloning, or set it
#                         back to the initial first unused state.
#                         runs inside the docker container

# abort on any errors
set -e

# check that we are in the expected directory
cd `dirname $0`/..

echo "==> Removing any local data..."
rm -fr media/
rm -fr data/
rm -fr static/


# Run the Bootstrap
script/bootstrap

# Create the database
script/migrate

# Run the data import
echo "==> Importing data..."
if [ "$1" = "--quick" ]; then
    echo "==> running quicker version of update"
    script/update
else
    script/update --all
fi
