#!/bin/bash

# abort on any errors
set -e

# check that we are in the expected directory
cd `dirname $0`/..

virtualenv_dir='../venv'
virtualenv_activate="$virtualenv_dir/bin/activate"
source $virtualenv_activate

"$(dirname "$0")/manage" test
