#!/bin/bash

# abort on any errors
set -e

# check that we are in the expected directory
cd `dirname $0`/..


"$(dirname "$0")/manage" preprocess  "$@"
"$(dirname "$0")/manage" add_authority_codes
"$(dirname "$0")/manage" add_council_websites
"$(dirname "$0")/manage" add_text "$@"
"$(dirname "$0")/manage" import_plans --confirm_changes
"$(dirname "$0")/manage" link_combined_authorities
"$(dirname "$0")/manage" add_related_councils "$@"
"$(dirname "$0")/manage" rebuild_index --noinput
"$(dirname "$0")/manage" import_emissions_data "$@"

