#!/bin/sh
sudo apt-get update

cd /vagrant

#fix dpkg-preconfigure error
export DEBIAN_FRONTEND=noninteractive

#upgrade local python3 to python3.6
cd /vagrant
sudo apt-get install -y libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm
sudo apt-get install -y libncurses5-dev  libncursesw5-dev xz-utils tk-dev libssl-dev zlib1g-dev
sudo apt-get install -y build-essential libpoppler-cpp-dev pkg-config python3-dev liblzma-dev

sudo wget https://www.python.org/ftp/python/3.6.12/Python-3.6.12.tgz
sudo tar xvf Python-3.6.12.tgz
cd Python-3.6.12
sudo ./configure --enable-optimizations --with-ssl=openssl
sudo make -j8
sudo make altinstall
sudo update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.6 1
sudo rm /usr/bin/lsb_release

# install the heroku command line tool
curl https://cli-assets.heroku.com/install.sh | sh

heroku plugins:install heroku-builds

cd /vagrant/caps

# Set up Python packages in a virtualenv
script/bootstrap

# Give permissions to vagrant user on all the packages
sudo chmod -R ugo+rwx /vagrant/venv
