# Generated by Django 3.2.7 on 2022-01-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_fix_score_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='planscore',
            name='top_performer',
            field=models.CharField(choices=[('single', 'Single Tier'), ('county', 'County Council'), ('district', 'District Council'), ('combined', 'Combined Authority'), ('northern-ireland', 'Northern Ireland Council')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plansection',
            name='top_performer',
            field=models.CharField(choices=[('single', 'Single Tier'), ('county', 'County Council'), ('district', 'District Council'), ('combined', 'Combined Authority'), ('northern-ireland', 'Northern Ireland Council')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plansectionscore',
            name='top_performer',
            field=models.CharField(choices=[('single', 'Single Tier'), ('county', 'County Council'), ('district', 'District Council'), ('combined', 'Combined Authority'), ('northern-ireland', 'Northern Ireland Council')], max_length=20, null=True),
        ),
    ]
