# Generated by Django 3.2.10 on 2022-01-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_add_top_performers'),
    ]

    operations = [
        migrations.AddField(
            model_name='planscore',
            name='deprivation_quintile',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planscore',
            name='political_control',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='planscore',
            name='population',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='planscore',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='planscore',
            name='ruc_cluster',
            field=models.CharField(blank=True, choices=[('urban', 'Urban'), ('rural', 'Rural'), ('urban-rural-areas', 'Urban with rural areas'), ('sparse-rural', 'Sparse and rural')], max_length=100, null=True),
        ),
    ]
