# Generated by Django 3.2.10 on 2022-02-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0005_add_scored_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='planquestion',
            name='parent',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
