# Generated by Django 3.2.10 on 2022-02-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0006_add_question_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='planquestionscore',
            name='max_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
