# Generated by Django 3.2.20 on 2023-09-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0007_add_question_score_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planquestionscore',
            name='score',
            field=models.SmallIntegerField(default=0),
        ),
    ]
