# Generated by Django 3.2.20 on 2023-09-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0009_alter_plansectionscore_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="planquestion",
            name="how_marked",
            field=models.CharField(
                choices=[
                    ("foi", "FOI"),
                    ("national_data", "National Data"),
                    ("volunteer", "Volunteer Research"),
                    ("national_volunteer", "National Data and Volunteer Research"),
                ],
                default="",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="planquestion",
            name="weighting",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("unweighted", "Unweighted"),
                ],
                default="low",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="planquestionscore",
            name="evidence_links",
            field=models.TextField(default="", null=True),
        ),
    ]
