# Generated by Django 3.2.20 on 2023-09-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0010_extra_question_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='planquestion',
            name='criteria',
            field=models.TextField(default='', null=True),
        ),
    ]
