# Generated by Django 3.2.20 on 2023-10-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0011_planquestion_criteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanQuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='planquestion',
            name='questiongroup',
            field=models.ManyToManyField(blank=True, null=True, to='scoring.PlanQuestionGroup'),
        ),
    ]
