# Generated by Django 3.2.20 on 2023-10-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0012_auto_20231002_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='planquestion',
            name='clarifications',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='planquestion',
            name='topic',
            field=models.TextField(default='', null=True),
        ),
    ]
