# Generated by Django 3.2.21 on 2023-10-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0013_auto_20231002_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansection',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
