# Generated by Django 3.2.21 on 2023-10-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0014_plansection_long_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planquestion',
            name='parent',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
