# Generated by Django 3.2.21 on 2023-10-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0015_alter_planquestion_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planquestion',
            name='questiongroup',
            field=models.ManyToManyField(to='scoring.PlanQuestionGroup'),
        ),
    ]
