# Generated by Django 3.2.21 on 2023-11-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0016_alter_planquestion_questiongroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planquestionscore',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
