# Generated by Django 4.2.17 on 2025-02-18 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0017_alter_planquestionscore_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="planscore",
            name="previous_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scoring.planscore",
            ),
        ),
    ]
