# Generated by Django 4.2.17 on 2025-03-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0018_planscore_previous_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="planscore",
            name="most_improved",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single Tier"),
                    ("county", "County Council"),
                    ("district", "District Council"),
                    ("combined", "Combined Authority"),
                    ("northern-ireland", "Northern Ireland Council"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="plansection",
            name="most_improved",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single Tier"),
                    ("county", "County Council"),
                    ("district", "District Council"),
                    ("combined", "Combined Authority"),
                    ("northern-ireland", "Northern Ireland Council"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="plansectionscore",
            name="most_improved",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single Tier"),
                    ("county", "County Council"),
                    ("district", "District Council"),
                    ("combined", "Combined Authority"),
                    ("northern-ireland", "Northern Ireland Council"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="planscore",
            name="top_performer",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single Tier"),
                    ("county", "County Council"),
                    ("district", "District Council"),
                    ("combined", "Combined Authority"),
                    ("northern-ireland", "Northern Ireland Council"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="plansection",
            name="top_performer",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single Tier"),
                    ("county", "County Council"),
                    ("district", "District Council"),
                    ("combined", "Combined Authority"),
                    ("northern-ireland", "Northern Ireland Council"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="plansectionscore",
            name="top_performer",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single Tier"),
                    ("county", "County Council"),
                    ("district", "District Council"),
                    ("combined", "Combined Authority"),
                    ("northern-ireland", "Northern Ireland Council"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
