# Generated by Django 4.2.17 on 2025-03-03 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0019_planscore_most_improved_plansection_most_improved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="planquestion",
            name="previous_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scoring.planquestion",
            ),
        ),
    ]
