# Generated by Django 4.2.17 on 2025-03-05 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0020_planquestion_previous_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("is_current", models.BooleanField(default=False)),
                ("new_council_date", models.DateField(blank=True, null=True)),
                ("old_council_date", models.DateField(blank=True, null=True)),
                (
                    "previous_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scoring.planyear",
                    ),
                ),
            ],
        ),
    ]
