# Generated by Django 4.2.17 on 2025-05-29 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0021_planyear"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanYearConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("value", models.JSONField()),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scoring.planyear",
                    ),
                ),
            ],
        ),
    ]
