# Generated by Django 2.2.8 on 2020-10-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='council',
            name='mapit_id',
        ),
        migrations.AddField(
            model_name='council',
            name='mapit_area_code',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
