# Generated by Django 2.2.8 on 2020-10-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0002_auto_20201016_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='council',
            name='authority_code',
            field=models.CharField(max_length=4),
        ),
    ]
