# Generated by Django 2.2.8 on 2020-10-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0003_auto_20201016_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandocument',
            name='document_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Action plan'), (2, 'Climate strategy'), (3, 'Summary document'), (4, 'Pre-plan'), (5, 'Meeting minutes')]),
        ),
        migrations.AlterField(
            model_name='plandocument',
            name='well_presented',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
