# Generated by Django 2.2.8 on 2020-10-23 16:41

import cape.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0011_auto_20201020_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='council',
            name='country',
            field=models.PositiveSmallIntegerField(choices=[(1, 'England'), (2, 'Scotland'), (3, 'Wales'), (4, 'Northern Ireland')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plandocument',
            name='file',
            field=models.FileField(storage=cape.models.OverwriteStorage(), upload_to='', verbose_name='plans'),
        ),
    ]
