# Generated by Django 2.2.8 on 2020-10-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0014_auto_20201027_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='council',
            name='gss_code',
            field=models.CharField(default='', max_length=9),
            preserve_default=False,
        ),
    ]
