# Generated by Django 2.2.8 on 2020-10-28 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0016_auto_20201028_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('value', models.DecimalField(decimal_places=12, max_digits=12)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caps.Council')),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caps.DataType')),
            ],
        ),
    ]
