# Generated by Django 2.2.8 on 2020-10-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0017_datapoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='value',
            field=models.DecimalField(decimal_places=20, max_digits=20),
        ),
    ]
