# Generated by Django 2.2.8 on 2020-10-30 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0021_auto_20201028_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='council',
            name='combined_authority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='caps.Council'),
        ),
    ]
