# Generated by Django 2.2.8 on 2020-11-12 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0024_auto_20201106_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datapoint',
            options={'ordering': ['data_type', 'year']},
        ),
    ]
