# Generated by Django 2.2.24 on 2021-09-16 16:08

from django.db import migrations
from django.db.models import F


def update_last_with_first(apps, schema_editor):
    PlanDocument = apps.get_model('caps', 'PlanDocument')
    PlanDocument.objects.all().update(date_last_found=F('date_first_found'))

class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0027_savedsearch'),
    ]

    operations = [
        migrations.RunPython(update_last_with_first),
    ]
