# Generated by Django 3.2.7 on 2021-10-19 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0028_council_promises'),
        ('caps', '0028_fix_first_and_last_found'),
    ]

    operations = [
    ]
