# Generated by Django 2.2.24 on 2021-09-21 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0029_merge_20211019_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyDeclaration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('date_declared', models.DateField(blank=True, null=True)),
                ('source_url', models.URLField(max_length=600)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caps.Council')),
            ],
        ),
    ]
