# Generated by Django 3.2.7 on 2021-11-08 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caps', '0031_council_twitter_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPlanDocument',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateField(blank=True, editable=False)),
                ('updated_at', models.DateField(blank=True, editable=False)),
                ('url', models.URLField(max_length=600)),
                ('url_hash', models.CharField(max_length=7)),
                ('date_first_found', models.DateField(blank=True, null=True)),
                ('date_last_found', models.DateField(blank=True, null=True)),
                ('start_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('document_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Action plan'), (2, 'Climate strategy'), (3, 'Summary document'), (4, 'Pre-plan'), (5, 'Meeting minutes')], null=True)),
                ('scope', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Council only'), (2, 'Whole area')], null=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Draft'), (2, 'Approved')], null=True)),
                ('well_presented', models.BooleanField(blank=True, null=True)),
                ('baseline_analysis', models.BooleanField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=800)),
                ('file_type', models.CharField(max_length=200)),
                ('charset', models.CharField(blank=True, max_length=50)),
                ('text', models.TextField(blank=True)),
                ('file', models.TextField(max_length=100, verbose_name='plans')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('council', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caps.council')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical plan document',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
