# Generated by Django 2.2.24 on 2021-10-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0033_historicalpromise'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='council_restriction',
            field=models.CharField(default='', help_text='The text used to restrict by council', max_length=1000),
        ),
    ]
