# Generated by Django 3.2.7 on 2021-12-09 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0034_savedseach_council_restriction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ComparisonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='council',
            name='related_councils',
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('match_score', models.FloatField()),
                ('position', models.IntegerField()),
                ('council_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances', to='caps.council')),
                ('council_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reverse_distance', to='caps.council')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caps.comparisontype')),
            ],
        ),
        migrations.CreateModel(
            name='ComparisonLabelAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caps.council')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caps.comparisonlabel')),
            ],
        ),
        migrations.AddField(
            model_name='comparisonlabel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caps.comparisontype'),
        ),
        migrations.AddField(
            model_name='council',
            name='labels',
            field=models.ManyToManyField(blank=True, through='caps.ComparisonLabelAssignment', to='caps.ComparisonLabel'),
        ),
        migrations.AddField(
            model_name='council',
            name='related_authorities',
            field=models.ManyToManyField(blank=True, related_name='_caps_council_related_authorities_+', through='caps.Distance', to='caps.Council'),
        ),
    ]
