# Generated by Django 3.2.12 on 2022-03-14 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0036_add_council_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonlabelassignment',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='caps.comparisonlabel'),
        ),
    ]
