# Generated by Django 3.2.12 on 2022-03-10 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0038_add_document_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField(default=0)),
                ('funding', models.CharField(blank=True, default='', max_length=300)),
                ('emission_source', models.CharField(blank=True, default='', max_length=100)),
                ('emission_savings', models.FloatField(default=0)),
                ('capital_cost', models.FloatField(default=0)),
                ('annual_cost', models.FloatField(default=0)),
                ('annual_savings', models.FloatField(default=0)),
                ('measurement_type', models.CharField(blank=True, choices=[('Actual', 'actual'), ('Estimated', 'estimated')], max_length=30)),
                ('lifespan', models.FloatField(default=0)),
                ('start_year', models.IntegerField(default=0)),
                ('comments', models.TextField(blank=True)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caps.council')),
            ],
        ),
    ]
