# Generated by Django 3.2.12 on 2022-04-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0039_council_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='council',
            name='county',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='council',
            name='region',
            field=models.CharField(choices=[('East Midlands', 'East Midlands'), ('East of England', 'East of England'), ('London', 'London'), ('North East', 'North East'), ('North West', 'North West'), ('Northern Ireland', 'Northern Ireland'), ('Scotland', 'Scotland'), ('South East', 'South East'), ('South West', 'South West'), ('Wales', 'Wales'), ('West Midlands', 'West Midlands'), ('Yorkshire and The Humber', 'Yorkshire and The Humber')], max_length=200, null=True),
        ),
    ]
