# Generated by Django 3.2.13 on 2022-08-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0042_add_council_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='council',
            name='authority_type',
            field=models.CharField(blank=True, choices=[('CC', 'City of London'), ('COMB', 'Combined Authority'), ('CTY', 'County Council'), ('LBO', 'London Borough'), ('MD', 'Metropolitan District'), ('NMD', 'Non-Metropolitan District'), ('UA', 'Unitary Authority'), ('NID', 'Northern Irish Council')], max_length=4),
        ),
    ]
